### PR TITLE
Fix process.dlopen link

### PR DESCRIPTION
**Pull request by michaeljones**
I assume it is meant to use standard markdown syntax and be a normal link.

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

- I like links :)

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Thanks

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by michaeljones** [comment]
For some reason, I can't see the CLA. I assumed there would be a bot post or something? I'm happy to close this and let you fix it directly if that is easier.

**Comment by alexander-akait** [comment]
This link https://cla.js.foundation/webpack-contrib/node-loader?pullRequest=44

**Comment by michaeljones** [comment]
Signed!

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
