### PR TITLE
chore: update installation command

### PR DESCRIPTION
**Pull request by amareshsm**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
update installation command

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
Can you run prettier on readme?

**Comment by amareshsm** [comment]
Please trigger workflows

**Comment by amareshsm** [comment]
Please trigger workflows

**Comment by amareshsm** [comment]
Bumping for review.

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
